/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-23 05:14:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.test1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" src=\"mydate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form style=\" border: 2px solid #dddd;width: 47%;padding-bottom:20px;padding-top:20px;\" id=\"form1\" name=\"form1\" method=\"get\" action=\"time.jsp\">\r\n");
      out.write("  \r\n");
      out.write("  <label>开始日期</label>\r\n");
      out.write("   <label>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("    <input type=\"text\" id=\"time\" name=\"time\" onfocus=\"MyCalendar.SetDate(this)\" value=\"\">\r\n");
      out.write("    </label>\r\n");
      out.write("     <label>开始时间\r\n");
      out.write("   \r\n");
      out.write("     <SELECT NAME=\"day\" style=\" width:175px\">\r\n");
      out.write("    \r\n");
      out.write("<option  value=\"00\">00</option>\r\n");
      out.write("<option  value=\"01\">01</option>\r\n");
      out.write("<option  value=\"02\">02</option>\r\n");
      out.write("<option  value=\"03\">03</option>\r\n");
      out.write("<option  value=\"04\">04</option>\r\n");
      out.write("<option  value=\"05\">05</option>\r\n");
      out.write("<option  value=\"06\">06</option>\r\n");
      out.write("<option  value=\"07\">07</option>\r\n");
      out.write("<option  value=\"08\">08</option>\r\n");
      out.write("<option  value=\"09\">09</option>\r\n");
      out.write("<option  value=\"10\">10</option>\r\n");
      out.write("<option  value=\"11\">11</option>\r\n");
      out.write("<option  value=\"12\">12</option>\r\n");
      out.write("<option  value=\"13\">13</option>\r\n");
      out.write("<option  value=\"14\">14</option>\r\n");
      out.write("<option  value=\"15\">15</option>\r\n");
      out.write("<option  value=\"16\">16</option>\r\n");
      out.write("<option  value=\"17\">17</option>\r\n");
      out.write("<option  value=\"18\">18</option>\r\n");
      out.write("<option  value=\"19\">19</option>\r\n");
      out.write("<option  value=\"20\">20</option>\r\n");
      out.write("<option  value=\"21\">21</option>\r\n");
      out.write("<option  value=\"22\">22</option>\r\n");
      out.write("<option  value=\"23\">23</option>\r\n");
      out.write("<option  value=\"24\">24</option>\r\n");
      out.write("\r\n");
      out.write("</SELECT>\r\n");
      out.write("    </label> \r\n");
      out.write("    \r\n");
      out.write("    <br><br>\r\n");
      out.write("    <label>截止日期</label>\r\n");
      out.write("   <label>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"text\" id=\"endtime\" name=\"endtime\" onfocus=\"MyCalendar.SetDate(this)\" value=\"\">\r\n");
      out.write("    </label>\r\n");
      out.write("     <label>截止时间\r\n");
      out.write("   \r\n");
      out.write("     <SELECT NAME=\"endday\" style=\" width:175px\">\r\n");
      out.write("    \r\n");
      out.write("<option  value=\"00\">00</option>\r\n");
      out.write("<option  value=\"01\">01</option>\r\n");
      out.write("<option  value=\"02\">02</option>\r\n");
      out.write("<option  value=\"03\">03</option>\r\n");
      out.write("<option  value=\"04\">04</option>\r\n");
      out.write("<option  value=\"05\">05</option>\r\n");
      out.write("<option  value=\"06\">06</option>\r\n");
      out.write("<option  value=\"07\">07</option>\r\n");
      out.write("<option  value=\"08\">08</option>\r\n");
      out.write("<option  value=\"09\">09</option>\r\n");
      out.write("<option  value=\"10\">10</option>\r\n");
      out.write("<option  value=\"11\">11</option>\r\n");
      out.write("<option  value=\"12\">12</option>\r\n");
      out.write("<option  value=\"13\">13</option>\r\n");
      out.write("<option  value=\"14\">14</option>\r\n");
      out.write("<option  value=\"15\">15</option>\r\n");
      out.write("<option  value=\"16\">16</option>\r\n");
      out.write("<option  value=\"17\">17</option>\r\n");
      out.write("<option  value=\"18\">18</option>\r\n");
      out.write("<option  value=\"19\">19</option>\r\n");
      out.write("<option  value=\"20\">20</option>\r\n");
      out.write("<option  value=\"21\">21</option>\r\n");
      out.write("<option  value=\"22\">22</option>\r\n");
      out.write("<option  value=\"23\">23</option>\r\n");
      out.write("<option  value=\"24\">24</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</SELECT>\r\n");
      out.write("    </label>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <label>\r\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" id=\"button\" value=\"查询\" />\r\n");
      out.write("    </label>\r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  <br><br>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <form style=\"border: 2px solid #dddd;width: 47%;padding-bottom:20px;padding-top:20px;\" id=\"form2\" name=\"form2\" method=\"get\" action=\"test.jsp\">\r\n");
      out.write("  \r\n");
      out.write("  <label>工单查询</label>\r\n");
      out.write("   <label>\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("    <input type=\"text\" id=\"workorder\" name=\"workorder\"  value=\"\">\r\n");
      out.write("    </label>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <label>\r\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" id=\"button\" value=\"查询\" />\r\n");
      out.write("    </label>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form style=\"border: 2px solid #dddd;width: 47%;padding-bottom:20px;padding-top:20px;\"  id=\"form3\" name=\"form3\" method=\"get\" action=\"line.jsp\">\r\n");
      out.write("  \r\n");
      out.write("  <label>开始日期</label>\r\n");
      out.write("   <label>\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("    <input type=\"text\" id=\"time\" name=\"time\" onfocus=\"MyCalendar.SetDate(this)\" value=\"\">\r\n");
      out.write("    </label>\r\n");
      out.write("     <label>开始时间\r\n");
      out.write("   \r\n");
      out.write("     <SELECT NAME=\"day\" style=\" width:175px\">\r\n");
      out.write("    \r\n");
      out.write("<option  value=\"00\">00</option>\r\n");
      out.write("<option  value=\"01\">01</option>\r\n");
      out.write("<option  value=\"02\">02</option>\r\n");
      out.write("<option  value=\"03\">03</option>\r\n");
      out.write("<option  value=\"04\">04</option>\r\n");
      out.write("<option  value=\"05\">05</option>\r\n");
      out.write("<option  value=\"06\">06</option>\r\n");
      out.write("<option  value=\"07\">07</option>\r\n");
      out.write("<option  value=\"08\">08</option>\r\n");
      out.write("<option  value=\"09\">09</option>\r\n");
      out.write("<option  value=\"10\">10</option>\r\n");
      out.write("<option  value=\"11\">11</option>\r\n");
      out.write("<option  value=\"12\">12</option>\r\n");
      out.write("<option  value=\"13\">13</option>\r\n");
      out.write("<option  value=\"14\">14</option>\r\n");
      out.write("<option  value=\"15\">15</option>\r\n");
      out.write("<option  value=\"16\">16</option>\r\n");
      out.write("<option  value=\"17\">17</option>\r\n");
      out.write("<option  value=\"18\">18</option>\r\n");
      out.write("<option  value=\"19\">19</option>\r\n");
      out.write("<option  value=\"20\">20</option>\r\n");
      out.write("<option  value=\"21\">21</option>\r\n");
      out.write("<option  value=\"22\">22</option>\r\n");
      out.write("<option  value=\"23\">23</option>\r\n");
      out.write("<option  value=\"24\">24</option>\r\n");
      out.write("\r\n");
      out.write("</SELECT>\r\n");
      out.write("    </label> \r\n");
      out.write("    \r\n");
      out.write("    <br><br>\r\n");
      out.write("    <label>截止日期</label>\r\n");
      out.write("   <label>\r\n");
      out.write("    \r\n");
      out.write("    <input type=\"text\" id=\"endtime\" name=\"endtime\" onfocus=\"MyCalendar.SetDate(this)\" value=\"\">\r\n");
      out.write("    </label>\r\n");
      out.write("     <label>截止时间\r\n");
      out.write("   \r\n");
      out.write("     <SELECT NAME=\"endday\" style=\" width:175px\">\r\n");
      out.write("    \r\n");
      out.write("<option  value=\"00\">00</option>\r\n");
      out.write("<option  value=\"01\">01</option>\r\n");
      out.write("<option  value=\"02\">02</option>\r\n");
      out.write("<option  value=\"03\">03</option>\r\n");
      out.write("<option  value=\"04\">04</option>\r\n");
      out.write("<option  value=\"05\">05</option>\r\n");
      out.write("<option  value=\"06\">06</option>\r\n");
      out.write("<option  value=\"07\">07</option>\r\n");
      out.write("<option  value=\"08\">08</option>\r\n");
      out.write("<option  value=\"09\">09</option>\r\n");
      out.write("<option  value=\"10\">10</option>\r\n");
      out.write("<option  value=\"11\">11</option>\r\n");
      out.write("<option  value=\"12\">12</option>\r\n");
      out.write("<option  value=\"13\">13</option>\r\n");
      out.write("<option  value=\"14\">14</option>\r\n");
      out.write("<option  value=\"15\">15</option>\r\n");
      out.write("<option  value=\"16\">16</option>\r\n");
      out.write("<option  value=\"17\">17</option>\r\n");
      out.write("<option  value=\"18\">18</option>\r\n");
      out.write("<option  value=\"19\">19</option>\r\n");
      out.write("<option  value=\"20\">20</option>\r\n");
      out.write("<option  value=\"21\">21</option>\r\n");
      out.write("<option  value=\"22\">22</option>\r\n");
      out.write("<option  value=\"23\">23</option>\r\n");
      out.write("<option  value=\"24\">24</option>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</SELECT>\r\n");
      out.write("    </label>\r\n");
      out.write("     <label>线别\r\n");
      out.write("   \r\n");
      out.write("     <SELECT NAME=\"line\" style=\" width:175px\">\r\n");
      out.write("    \r\n");
      out.write("<option  value=\"LED_L01\">LED_L01</option>\r\n");
      out.write("<option  value=\"LED_L02\">LED_L02</option>\r\n");
      out.write("<option  value=\"LED_L03\">LED_L03</option>\r\n");
      out.write("<option  value=\"LED_L04\">LED_L04</option>\r\n");
      out.write("<option  value=\"LED_L05\">LED_L05</option>\r\n");
      out.write("<option  value=\"LED_L06\">LED_L06</option>\r\n");
      out.write("<option  value=\"LED_L07\">LED_L07</option>\r\n");
      out.write("<option  value=\"LED_L08\">LED_L08</option>\r\n");
      out.write("<option  value=\"LED_L09\">LED_L09</option>\r\n");
      out.write("<option  value=\"LED_S01\">LED_S01</option>\r\n");
      out.write("<option  value=\"LED_S02\">LED_S02</option>\r\n");
      out.write("<option  value=\"LED_S03\">LED_S03</option>\r\n");
      out.write("<option  value=\"LED_S04\">LED_S04</option>\r\n");
      out.write("<option  value=\"LED_S05\">LED_S05</option>\r\n");
      out.write("<option  value=\"LED_S06\">LED_S06</option>\r\n");
      out.write("<option  value=\"LED_TP1\">LED_TP1</option>\r\n");
      out.write("<option  value=\"LED_TP2\">LED_TP2</option>\r\n");
      out.write("<option  value=\"LED_TP3\">LED_TP3</option>\r\n");
      out.write("<option  value=\"LED_W01\">LED_W01</option>\r\n");
      out.write("<option  value=\"LED_W02\">LED_W02</option>\r\n");
      out.write("<option  value=\"LED_W03\">LED_W03</option>\r\n");
      out.write("<option  value=\"LED_W04\">LED_W04</option>\r\n");
      out.write("<option  value=\"LED_W05\">LED_W05</option>\r\n");
      out.write("<option  value=\"LED_W06\">LED_W06</option>\r\n");
      out.write("<option  value=\"LED_W07\">LED_W07</option>\r\n");
      out.write("<option  value=\"LED_W08\">LED_W08</option>\r\n");
      out.write("<option  value=\"LED_W09\">LED_W09</option>\r\n");
      out.write("<option  value=\"LED_W10\">LED_W10</option>\r\n");
      out.write("<option  value=\"LED_W11\">LED_W11</option>\r\n");
      out.write("<option  value=\"LED_W12\">LED_W12</option>\r\n");
      out.write("<option  value=\"LED_W13\">LED_W13</option>\r\n");
      out.write("<option  value=\"LED_W14\">LED_W14</option>\r\n");
      out.write("<option  value=\"LED_W15\">LED_W15</option>\r\n");
      out.write("<option  value=\"LED_W16\">LED_W16</option>\r\n");
      out.write("<option  value=\"LED_S99\">LED_S99</option>\r\n");
      out.write("<option  value=\"LED_L99\">LED_L99</option>\r\n");
      out.write("<option  value=\"LED_W99\">LED_W99</option>\r\n");
      out.write("<option  value=\"LED_T99\">LED_T99</option>\r\n");
      out.write("</SELECT>\r\n");
      out.write("    </label> \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <label>\r\n");
      out.write("    &nbsp;&nbsp;&nbsp;&nbsp;<input type=\"submit\" id=\"button\" value=\"查询\" />\r\n");
      out.write("    </label>\r\n");
      out.write("    \r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
