//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace winfrom111.w {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getValueOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback shujuchaxunOperationCompleted;
        
        private System.Threading.SendOrPostCallback ziduantiaojianOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataSetBytesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataSetSurrogateZipBytesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::winfrom111.Properties.Settings.Default.winfrom111_localhost_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getValueCompletedEventHandler getValueCompleted;
        
        /// <remarks/>
        public event SendmailCompletedEventHandler SendmailCompleted;
        
        /// <remarks/>
        public event shujuchaxunCompletedEventHandler shujuchaxunCompleted;
        
        /// <remarks/>
        public event ziduantiaojianCompletedEventHandler ziduantiaojianCompleted;
        
        /// <remarks/>
        public event GetDataSetBytesCompletedEventHandler GetDataSetBytesCompleted;
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataSetSurrogateZipBytesCompletedEventHandler GetDataSetSurrogateZipBytesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getValue", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getValue(string name) {
            object[] results = this.Invoke("getValue", new object[] {
                        name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getValueAsync(string name) {
            this.getValueAsync(name, null);
        }
        
        /// <remarks/>
        public void getValueAsync(string name, object userState) {
            if ((this.getValueOperationCompleted == null)) {
                this.getValueOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetValueOperationCompleted);
            }
            this.InvokeAsync("getValue", new object[] {
                        name}, this.getValueOperationCompleted, userState);
        }
        
        private void OngetValueOperationCompleted(object arg) {
            if ((this.getValueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getValueCompleted(this, new getValueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Sendmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Sendmail(string textBox4, string textBox5, string textBox6, string richTextBox1, string textBox7) {
            this.Invoke("Sendmail", new object[] {
                        textBox4,
                        textBox5,
                        textBox6,
                        richTextBox1,
                        textBox7});
        }
        
        /// <remarks/>
        public void SendmailAsync(string textBox4, string textBox5, string textBox6, string richTextBox1, string textBox7) {
            this.SendmailAsync(textBox4, textBox5, textBox6, richTextBox1, textBox7, null);
        }
        
        /// <remarks/>
        public void SendmailAsync(string textBox4, string textBox5, string textBox6, string richTextBox1, string textBox7, object userState) {
            if ((this.SendmailOperationCompleted == null)) {
                this.SendmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendmailOperationCompleted);
            }
            this.InvokeAsync("Sendmail", new object[] {
                        textBox4,
                        textBox5,
                        textBox6,
                        richTextBox1,
                        textBox7}, this.SendmailOperationCompleted, userState);
        }
        
        private void OnSendmailOperationCompleted(object arg) {
            if ((this.SendmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/shujuchaxun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet shujuchaxun(string work_order, string startime, string endtiem) {
            object[] results = this.Invoke("shujuchaxun", new object[] {
                        work_order,
                        startime,
                        endtiem});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void shujuchaxunAsync(string work_order, string startime, string endtiem) {
            this.shujuchaxunAsync(work_order, startime, endtiem, null);
        }
        
        /// <remarks/>
        public void shujuchaxunAsync(string work_order, string startime, string endtiem, object userState) {
            if ((this.shujuchaxunOperationCompleted == null)) {
                this.shujuchaxunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnshujuchaxunOperationCompleted);
            }
            this.InvokeAsync("shujuchaxun", new object[] {
                        work_order,
                        startime,
                        endtiem}, this.shujuchaxunOperationCompleted, userState);
        }
        
        private void OnshujuchaxunOperationCompleted(object arg) {
            if ((this.shujuchaxunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.shujuchaxunCompleted(this, new shujuchaxunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ziduantiaojian", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ziduantiaojian(string ziduan, string biaoming, string tiaojian) {
            object[] results = this.Invoke("ziduantiaojian", new object[] {
                        ziduan,
                        biaoming,
                        tiaojian});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ziduantiaojianAsync(string ziduan, string biaoming, string tiaojian) {
            this.ziduantiaojianAsync(ziduan, biaoming, tiaojian, null);
        }
        
        /// <remarks/>
        public void ziduantiaojianAsync(string ziduan, string biaoming, string tiaojian, object userState) {
            if ((this.ziduantiaojianOperationCompleted == null)) {
                this.ziduantiaojianOperationCompleted = new System.Threading.SendOrPostCallback(this.OnziduantiaojianOperationCompleted);
            }
            this.InvokeAsync("ziduantiaojian", new object[] {
                        ziduan,
                        biaoming,
                        tiaojian}, this.ziduantiaojianOperationCompleted, userState);
        }
        
        private void OnziduantiaojianOperationCompleted(object arg) {
            if ((this.ziduantiaojianCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ziduantiaojianCompleted(this, new ziduantiaojianCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataSetBytes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetDataSetBytes(string vCmd) {
            object[] results = this.Invoke("GetDataSetBytes", new object[] {
                        vCmd});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataSetBytesAsync(string vCmd) {
            this.GetDataSetBytesAsync(vCmd, null);
        }
        
        /// <remarks/>
        public void GetDataSetBytesAsync(string vCmd, object userState) {
            if ((this.GetDataSetBytesOperationCompleted == null)) {
                this.GetDataSetBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataSetBytesOperationCompleted);
            }
            this.InvokeAsync("GetDataSetBytes", new object[] {
                        vCmd}, this.GetDataSetBytesOperationCompleted, userState);
        }
        
        private void OnGetDataSetBytesOperationCompleted(object arg) {
            if ((this.GetDataSetBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataSetBytesCompleted(this, new GetDataSetBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetData(string vCmd) {
            object[] results = this.Invoke("GetData", new object[] {
                        vCmd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(string vCmd) {
            this.GetDataAsync(vCmd, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(string vCmd, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        vCmd}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDataSetSurrogateZipBytes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetDataSetSurrogateZipBytes(string vCmd) {
            object[] results = this.Invoke("GetDataSetSurrogateZipBytes", new object[] {
                        vCmd});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataSetSurrogateZipBytesAsync(string vCmd) {
            this.GetDataSetSurrogateZipBytesAsync(vCmd, null);
        }
        
        /// <remarks/>
        public void GetDataSetSurrogateZipBytesAsync(string vCmd, object userState) {
            if ((this.GetDataSetSurrogateZipBytesOperationCompleted == null)) {
                this.GetDataSetSurrogateZipBytesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataSetSurrogateZipBytesOperationCompleted);
            }
            this.InvokeAsync("GetDataSetSurrogateZipBytes", new object[] {
                        vCmd}, this.GetDataSetSurrogateZipBytesOperationCompleted, userState);
        }
        
        private void OnGetDataSetSurrogateZipBytesOperationCompleted(object arg) {
            if ((this.GetDataSetSurrogateZipBytesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataSetSurrogateZipBytesCompleted(this, new GetDataSetSurrogateZipBytesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void getValueCompletedEventHandler(object sender, getValueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getValueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getValueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SendmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void shujuchaxunCompletedEventHandler(object sender, shujuchaxunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class shujuchaxunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal shujuchaxunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ziduantiaojianCompletedEventHandler(object sender, ziduantiaojianCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ziduantiaojianCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ziduantiaojianCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataSetBytesCompletedEventHandler(object sender, GetDataSetBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataSetBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataSetBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetDataSetSurrogateZipBytesCompletedEventHandler(object sender, GetDataSetSurrogateZipBytesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataSetSurrogateZipBytesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataSetSurrogateZipBytesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591